version: "3.8"

services:
  frontend:
    build: ./myapp
    ports:
      - "3000:80"
    depends_on:
      - localhost

  localhost:
    image: node:18
    working_dir: /app
    volumes:
      - ./json:/app
    command: npx json-server --watch db.json --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"